version: "3.9"

networks:
  my-network:
    ipam:
      config:
      - subnet: 10.17.0.0/24
    driver:
      bridge

services:
  web1:
    build: ./web1
    image: web01
    container_name: web01
    volumes:
      - ./web1/volumeweb1:/usr/share/nginx/html
    networks:
      my-network:
        ipv4_address: 10.17.0.2

  web2:
    build: ./web2
    image: web02
    container_name: web02
    volumes:
      - ./web2/volumeweb2:/usr/share/nginx/html
    networks:
      my-network:
        ipv4_address: 10.17.0.3

  proxy:
    build: ./proxy
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
    networks:
      my-network:
        ipv4_address: 10.17.0.4
    depends_on:
      - "web01"
      - "web02"